/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Владелец
 */
public class Balance extends javax.swing.JFrame {

    private Connection dbConnection;

    /**
     * Creates new form NewJFrame
     */
    public Balance() {
        initComponents();
        dbConnection = getConnection();
        tableShow();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Остаток товаров");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(100, 100));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 362;
        gridBagConstraints.ipady = 375;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(32, 44, 183, 55);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public Connection getConnection() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException e) {
            System.out.println(e.getMessage());
        }
        if (dbConnection != null) {
            return dbConnection;
        } else {
            try {
                dbConnection = DriverManager.getConnection("jdbc:mysql://localhost/test", "root", "08071994");
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }
            return dbConnection;
        }
    }

    private void tableShow() {
        dbConnection = getConnection();
        PreparedStatement pstmt = null;
        ResultSet rs = null;
        String balance = "SELECT p.name Имя,p.provider Поставщик,(IF(t2.number IS NOT NULL,t2.number,0) - IF(t1.number IS NOT NULL,t1.number,0)) Количество, p.price Цена\n"
                + "FROM \n"
                + " production p\n"
                + "LEFT JOIN \n"
                + " (SELECT p.name ,SUM(c.number) number\n"
                + "  FROM production p\n"
                + "  LEFT JOIN consumption c ON p.name = c.name\n"
                + "  GROUP BY p.name) t1 ON t1.name = p.name\n"
                + "LEFT JOIN \n"
                + " (SELECT p.name ,SUM(s.number) number\n"
                + "  FROM production p\n"
                + "  LEFT JOIN storage s ON p.name = s.name\n"
                + "  GROUP BY p.name) t2 ON p.name = t2.name";
        DefaultTableModel dtm = null;

        try {
            pstmt = dbConnection.prepareStatement(balance);
            dtm = new DefaultTableModel();

            if (pstmt.execute()) {
                rs = pstmt.getResultSet();

                //Формируем заголовки столбцов из названия полей -->
                ResultSetMetaData rsmd = rs.getMetaData();

                for (int col = 1; col <= rsmd.getColumnCount(); col++) {
                    dtm.addColumn(rsmd.getColumnLabel(col));

                }
                // <--
                while (rs.next()) {
                    Vector<String> row = new Vector<String>(); //Строка таблицы
                    /*Снова с помощью метаданных узнаем количество столбцов 
                     * в результате запроса и ниже в switch'е в зависимости 
                     * от типа текущего столбца забираем данные из ResultSet`a и пишем в 
                     * текущую строку - row. 
                     * */
                    for (int col = 1; col <= rsmd.getColumnCount(); col++) {
                        int type = rsmd.getColumnType(col);
                        switch (type) {

                            case Types.INTEGER:
                                row.add(Integer.toString(rs.getInt(col)));
                                break;

                            case Types.VARCHAR:
                                row.add(rs.getString(col));
                                break;

                            case Types.DECIMAL:
                                row.add(Double.toString(rs.getDouble(col)));
                                break;
                            default:
                                /*В этой моей тестовой таблице всего два типа полей: целое и строка. 
                                 *Соответственно если в таблице/запросе типов больше, то этот switch 
                                 *нужно расширить соответствующими типами, а сейчас, в случае если мы 
                                 *встретим неизвестный коду тип поля, я для наглядности бросаю исключение.                                    
                                 * */
                                throw new Exception("Неподдерживаемый тип");
                        }

                    }

                    dtm.addRow(row);
                }
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());

        } catch (Exception e) {
            e.printStackTrace();
        }
        jTable1.setModel(dtm);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Balance.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Balance.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Balance.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Balance.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Balance().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
